### PR TITLE
Added TVmaze Guide implementation using TVmaze's JSON-based REST API.

### PR DESCRIPTION
**Pull request by drauch**
See https://github.com/RoliSoft/RS-TV-Show-Tracker/issues/5.

### CODE REVIEW

**Comment by drauch** [comment]
(unfortunately not unit test yet, still have the issue to execute the tests, see #5).

**Comment by drauch** [comment]
Wow, that was fast! Looking forwards to the (hopefully soon-to-be) release :+1:

**Comment by RoliSoft** [comment]
There were a few issues, mostly JSON properties being accessed incorrectly. I've fixed them, and integrating TVmaze into the whole app as we speak.

**Comment by drauch** [comment]
:+1: thanks, gonna install the nightly build immediately ;)

Out of curiosity: you removed all my unit tests - any reason why?

**Comment by RoliSoft** [comment]
Mainly two reasons, first of all there are unit tests written in the base class, which R# can take and run for every subclass. Also, in your tests you were testing if specific properties equal specific strings, e.g. the cover URL or the beginning of the description. It is not a good idea to test this directly, since these will change as the database gets updated at the source, and the unit tests will start failing, even though they shouldn't be failing: the parser works, only the data changed.

**Comment by drauch** [comment]
I deliberately chose test data which is probably not changing, but you're right, in the end I can't be sure. Thanks for the clarification.

**Pull request merged**
